<?php

namespace AppBundle\Repository;

/**
 * Lab1_pomiar_tabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lab1_pomiar_tabRepository extends \Doctrine\ORM\EntityRepository
{
}
