<?php

namespace AppBundle\Repository;

/**
 * Lab1_wynikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lab1_wynikRepository extends \Doctrine\ORM\EntityRepository
{
}
