<?php

namespace AppBundle\Repository;

/**
 * Lab2_pomiarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lab2_pomiarRepository extends \Doctrine\ORM\EntityRepository
{
}
