<?php

namespace AppBundle\Repository;

/**
 * ZespolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZespolRepository extends \Doctrine\ORM\EntityRepository
{
}
