app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@AppBundle/Admin/"
    type:     annotation

_user_bundle:
  resource: "@UserBundle/Resources/config/routing.yml"

#user_rest:
#  resource: "@UserBundle/Controller/"
#  type:     annotation
#  prefix:   /rest
#  defaults:
#      _format: json